#服务配置
server:
  port: 80

spring:
  #  持久层
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/veeboot?
         useUnicode=true&characterEncoding=utf-8
    username: root
    password: q1w2e3
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource






mybatis:
  #  实体类
  type-aliases-package: com.teavamc
  #  mapper文件扫描位置
  mapper-locations: classpath:mapper/*.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

